[versions]
useanybrowser = "0.3.0"
kotlin = "2.0.0"
buildconfig = "5.4.0"
gradle-publish = "1.2.1"
nexus-publish = "2.0.0"
detekt = "1.23.6"
nodejs = "18.14.1"
yarn = "1.22.19"

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
useanybrowser = { id = "com.goncalossilva.useanybrowser", version.ref = "useanybrowser" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
gradle-publish = { id = "com.gradle.plugin-publish", version.ref = "gradle-publish" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus-publish" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
